adds lolin s3 pro
platformio/platform-espressif32 pull request #1303
Opened 2024-02-08 06:38 UTC by bsdlp

took hwid from https://github.com/espressif/arduino-esp32/blob/c21a8cdaa56822b13e6f8259ca5b5b1f7b5d88ae/variants/lolin_s3_pro/pins_arduino.h#L8

2024-02-08 11:15 UTC, valeros requested changes

2024-02-08 11:15 UTC, valeros commented on boards/lolin_s3_pro.json
> +      "-DARDUINO_USB_CDC_ON_BOOT=1",
Are you sure the `-DARDUINO_USB_CDC_ON_BOOT=1` macro is necessary? In the boards.txt it's [disabled](https://github.com/espressif/arduino-esp32/blob/master/boards.txt#L8140) by default.

2024-02-08 11:15 UTC, valeros commented on boards/lolin_s3_pro.json
> +    "variant": "lolin_s3"
Probably should be `lolin_s3_pro`.

2024-02-08 11:15 UTC, valeros commented on boards/lolin_s3_pro.json
> +}
EOF is missing.

2024-02-08 12:27 UTC, valeros commented
Hi @bsdlp, thanks for the PR, please review comments below.

2024-02-08 20:27 UTC, bsdlp commented
thanks @valeros i've addressed your comments

2024-02-09 10:53 UTC, valeros approved these changes

2024-02-09 11:36 UTC, merged

2024-02-09 11:37 UTC, valeros commented
Thanks, merged.