fixed waveshare_esp32_s3_touch_lcd_169 waveshare_esp32_s3_lcd_169 bugs, Added variant for Waveshare ESP32-S3-Zero
platformio/platform-espressif32 pull request #1448
Opened 2024-08-26 07:14 UTC by Y1hsiaochunnn

## Description of Change
fixed waveshare_esp32_s3_touch_lcd_169 waveshare_esp32_s3_lcd_169 bugs,
They're mentioned here:https://github.com/platformio/platform-espressif32/pull/1436

Added variant for Waveshare ESP32-S3-Zero

## Tests scenarios
Untested, pin definition is based on information in Waveshare wiki.

## Related links

https://www.waveshare.com/wiki/ESP32-S3-Zero

arduino-esp32 PR https://github.com/espressif/arduino-esp32/pull/10241

2024-08-26 14:42 UTC, valeros requested changes

2024-08-26 14:42 UTC, valeros commented on boards/waveshare-esp32-s3-zero.json
> +      "-DARDUINO_ESP32_S3_ZERO",
Shouldn't it be `-DARDUINO_WAVESHARE_ESP32_S3_ZERO`?

The same applies for the boards below.

2024-08-26 14:42 UTC, valeros commented on boards/waveshare-esp32-s3-zero.json
> +    ],
Aren't the `-DARDUINO_RUNNING_CORE=1` and `-DARDUINO_EVENT_RUNNING_CORE=1` macros needed here?

2024-08-26 14:44 UTC, valeros commented
Hi @Y1hsiaochunnn, please review my comments above.

2024-08-27 01:04 UTC, Y1hsiaochunnn commented
Hi @valeros,
revised it according to your suggestion

2024-08-27 09:10 UTC, Y1hsiaochunnn commented
thanks alot

2024-08-27 09:11 UTC, valeros approved these changes

2024-09-02 06:46 UTC, Y1hsiaochunnn commented
Hi @valeros ,
arduino-esp32 has pre-released V.3.1.0-RC1 and has merged ESP32-S3-Touch-LCD-1.69, ESP32-S3-LCD-1.69 and ESP32-S3-Zero. Is platformio ready to merge this pr and release it?

2024-09-02 08:39 UTC, valeros commented
@Y1hsiaochunnn As I already mentioned above, the PR will be merged once support for Arduino core v3 is added, see #1225

2026-07-29 10:43 UTC, closed without merging